pipeline {
	agent any
	stages {
		stage('Init') {
			steps {
				echo 'Hi. This is my first pipeline'
				echo 'This is Init stage'
			}
		}
		stage('Build') {
			steps {
				echo 'This is build stage'
			}
		}
		stage('Deploy') {
			steps {
				echo 'This is deploy stage'
			}
		}
		stage('Deploy_Production') {
			steps {
				echo 'Deploying to production!'
			}
		}
	}
}
 
